### ISSUE TITLE
Hard code

### ISSUE THREAD

**Issue by iamtodor** [dingran/angellist-webscrape#1]
Hello sir,
I have tried to run you code as is, but faced hard code dir path:
`self.working_dir = '/Users/dingran/github/angellist-webscrape'` in code/AngelScraper.py

Even when I fixed this path with my own another issue was raised:
```
angellist-webscrape $ sudo python2.7 code/main.py
2018-04-12 14:36:23.860029 Reading url list file: /Users/iamtodor/other/angellist-webscrape/output/url_lists/url_list_2018-04-12.csv
Traceback (most recent call last):
  File "code/main.py", line 5, in <module>
    a.generate_url_list_of_search_pages(use_existing_url_list=True)
  File "/Users/iamtodor/other/angellist-webscrape/code/AngelScraper.py", line 379, in generate_url_list_of_search_pages
    self.url_df = pd.read_csv(self.search_page_url_list_file)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 402, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File /Users/iamtodor/other/angellist-webscrape/output/url_lists/url_list_2018-04-12.csv does not exist
angellist-webscrape $
```

Can we do something with this?

**Comment by dingran** [comment]
Hi @iamtodor it looks like the problem is with a.generate_url_list_of_search_pages(use_existing_url_list=True)

you should set use_existing_url_list=False, since you don't have any existing url list.

Sorry about the lack of documentation for this.

BTW, I wrote these webscrapers a while back (for Angelist and other sites). I think nowadays, some of the sites are much less friendly to crawling. You can look into this https://scrapy.org/ as a better alternative.
